# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: example.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class ExampleServerServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/proto.ExampleServer"
		self._endpoints = {
			"MyFunction": Endpoint(
				service_name="ExampleServer",
				name="MyFunction",
				function=getattr(service, "MyFunction"),
				input=_sym_db.GetSymbol("proto.MyFunctionRequest"),
				output=_sym_db.GetSymbol("proto.MyFunctionResponse"),
			),
			"Sum": Endpoint(
				service_name="ExampleServer",
				name="Sum",
				function=getattr(service, "Sum"),
				input=_sym_db.GetSymbol("proto.SumRequest"),
				output=_sym_db.GetSymbol("proto.SumResponse"),
			),
		}

class ExampleServerClient(TwirpClient):

	def MyFunction(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/proto.ExampleServer/MyFunction",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("proto.MyFunctionResponse"),
			**kwargs,
		)

	def Sum(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/proto.ExampleServer/Sum",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("proto.SumResponse"),
			**kwargs,
		)
