# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\006/proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x05proto\"C\n\x11MyFunctionRequest\x12\x1d\n\x06\x63lient\x18\x01 \x01(\x0e\x32\r.proto.Client\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x12MyFunctionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\nSumRequest\x12\r\n\x05\x66irst\x18\x01 \x01(\x03\x12\x0e\n\x06second\x18\x02 \x01(\x03\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x03*\x1c\n\x06\x43lient\x12\x06\n\x02GO\x10\x00\x12\n\n\x06PYTHON\x10\x01\x32\x84\x01\n\rExampleServer\x12\x43\n\nMyFunction\x12\x18.proto.MyFunctionRequest\x1a\x19.proto.MyFunctionResponse\"\x00\x12.\n\x03Sum\x12\x11.proto.SumRequest\x1a\x12.proto.SumResponse\"\x00\x42\x08Z\x06/protob\x06proto3'
)

_CLIENT = _descriptor.EnumDescriptor(
  name='Client',
  full_name='proto.Client',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PYTHON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=208,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_CLIENT)

Client = enum_type_wrapper.EnumTypeWrapper(_CLIENT)
GO = 0
PYTHON = 1



_MYFUNCTIONREQUEST = _descriptor.Descriptor(
  name='MyFunctionRequest',
  full_name='proto.MyFunctionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client', full_name='proto.MyFunctionRequest.client', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.MyFunctionRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=91,
)


_MYFUNCTIONRESPONSE = _descriptor.Descriptor(
  name='MyFunctionResponse',
  full_name='proto.MyFunctionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.MyFunctionResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=130,
)


_SUMREQUEST = _descriptor.Descriptor(
  name='SumRequest',
  full_name='proto.SumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='proto.SumRequest.first', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='second', full_name='proto.SumRequest.second', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=175,
)


_SUMRESPONSE = _descriptor.Descriptor(
  name='SumResponse',
  full_name='proto.SumResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='proto.SumResponse.result', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=206,
)

_MYFUNCTIONREQUEST.fields_by_name['client'].enum_type = _CLIENT
DESCRIPTOR.message_types_by_name['MyFunctionRequest'] = _MYFUNCTIONREQUEST
DESCRIPTOR.message_types_by_name['MyFunctionResponse'] = _MYFUNCTIONRESPONSE
DESCRIPTOR.message_types_by_name['SumRequest'] = _SUMREQUEST
DESCRIPTOR.message_types_by_name['SumResponse'] = _SUMRESPONSE
DESCRIPTOR.enum_types_by_name['Client'] = _CLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyFunctionRequest = _reflection.GeneratedProtocolMessageType('MyFunctionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MYFUNCTIONREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:proto.MyFunctionRequest)
  })
_sym_db.RegisterMessage(MyFunctionRequest)

MyFunctionResponse = _reflection.GeneratedProtocolMessageType('MyFunctionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MYFUNCTIONRESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:proto.MyFunctionResponse)
  })
_sym_db.RegisterMessage(MyFunctionResponse)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:proto.SumRequest)
  })
_sym_db.RegisterMessage(SumRequest)

SumResponse = _reflection.GeneratedProtocolMessageType('SumResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMRESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:proto.SumResponse)
  })
_sym_db.RegisterMessage(SumResponse)


DESCRIPTOR._options = None

_EXAMPLESERVER = _descriptor.ServiceDescriptor(
  name='ExampleServer',
  full_name='proto.ExampleServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=239,
  serialized_end=371,
  methods=[
  _descriptor.MethodDescriptor(
    name='MyFunction',
    full_name='proto.ExampleServer.MyFunction',
    index=0,
    containing_service=None,
    input_type=_MYFUNCTIONREQUEST,
    output_type=_MYFUNCTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='proto.ExampleServer.Sum',
    index=1,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLESERVER)

DESCRIPTOR.services_by_name['ExampleServer'] = _EXAMPLESERVER

# @@protoc_insertion_point(module_scope)
